meta_product_name: "Vesper"
meta_title: "Fun should be planned!"
meta_description: "Easily organize your night out with friends!"
meta_image: "vesper.png"                       # should exist in `app/assets/images/`
